Don't show 999999.0 value on CGM when a line or transformer has no Imax
powsybl/powsybl-core pull request #1444
Opened 2020-08-17 08:27 UTC by NajjariBelgacem

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*

**What is the current behavior?** *(You can also link to an open issue here)*

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change or deprecate an API?** *If yes, check the following:*
- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration guide has been updated in the github wiki *(What changes might users need to make in their application due to this PR?)*

**Other information**:

(if any of the questions/checkboxes don't apply, please delete them entirely)

2020-08-25 11:30 UTC, murgeyseb requested changes

2020-08-25 11:30 UTC, murgeyseb commented on ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/UcteExporter.java
> +                LOGGER.warn("Switch {}: No current limit, set value to {}", sw.getId(), null);
As the current limit is not set, you can replace the message. For example:
No current limit provided

2020-08-25 11:30 UTC, murgeyseb commented on ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/util/UcteConstants.java
> +    public static final Integer DEFAULT_MAX_CURRENT = 999999;
Is this constant still needed now ?

2020-09-08 09:12 UTC, murgeyseb requested changes

2020-09-08 09:12 UTC, murgeyseb commented on ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/UcteExporter.java
> +            if (!permanentLimit2.isPresent()) {
else !

2020-09-08 09:12 UTC, murgeyseb commented on ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/UcteExporter.java
> +            if (!permanentLimit2.isPresent()) {
else !

2020-09-21 14:07 UTC, mathbagu requested changes
Looking to the UCTE-DEF specification, the current limit of a line or a two windings transformer is mandatory. Could you quote the specification you use to change this behavior.

I'm also suprized that there are no unit-tests in that PR. Could you please provide at least a test case to show that everything works properly if there is no current limits for a line and a 2WT.

2020-09-21 14:16 UTC, murgeyseb commented
For the content of the PR, Document "Quality of datasets and calculation" from ENTSO-E is not accorded to what is in the UCTE format description.

It's true that in UCTE format document nothing says that Imax is optional. However, in "Quality of datasets and calculation", it is stated those requirements:
- DATA-LINE-IMAX-02 : Line max current limit / WARNING / Equivalent line current limit must be
positive or blank
- DATA-LINE-IMAX-03 : Line max current limit / WARNING / Busbar coupler current limit must
be positive or blank
- DATA-TRF-IMAX-02: Transformer current limit (non-regulated winding) / WARNING / Equivalent transformer current limit
must be positive or blank

That may explains why in real data we get elements without imax value. And we are not supposed to modify users data.

2020-09-21 14:19 UTC, murgeyseb commented
I just realised that this PR is an old one (not closed). The actual merged one is here (#1465)

2020-09-21 14:36 UTC, closed without merging