Implement TopologyTraverserAdapter to traverse mergingview from TerminalAdapter
powsybl/powsybl-core pull request #1452
Opened 2020-08-28 13:30 UTC by MioRtia

Signed-off-by: RALAMBOTIANA MIORA <miora.ralambotiana@rte-france.com>

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*

**What is the current behavior?** *(You can also link to an open issue here)*

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change or deprecate an API?** *If yes, check the following:*
- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration guide has been updated in the github wiki *(What changes might users need to make in their application due to this PR?)*

**Other information**:

(if any of the questions/checkboxes don't apply, please delete them entirely)

2020-08-28 14:14 UTC, floriand-e2r requested changes

2020-08-28 14:14 UTC, floriand-e2r commented on iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/TerminalAdapter.java
>      // -------------------------------
You can remove these lines now :partying_face:

2020-08-28 15:32 UTC, annetill approved these changes
Thanks Miora, this PR resolves the error I found when I tried to perform a security analysis over the merging view. The simulator I have used is Hades2 and I still have to test with the OpenLoadFlow but at this stage of developpement, I is not relevant to do it. I still need to compare SA results from a classical network and from the merging view but it is not urgent.

2020-08-31 10:18 UTC, floriand-e2r approved these changes

2020-08-31 10:19 UTC, annetill approved these changes

2020-08-31 10:20 UTC, merged