[wip] Add new iidm hvdc extensions
powsybl/powsybl-core pull request #1587
Opened 2021-01-08 16:05 UTC by pl-buiquang

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*
feature

**What is the current behavior?** *(You can also link to an open issue here)*

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change or deprecate an API?** *If yes, check the following:*
- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration guide has been updated in the github wiki *(What changes might users need to make in their application due to this PR?)*

**Other information**:

(if any of the questions/checkboxes don't apply, please delete them entirely)

2021-01-15 14:02 UTC, MioRtia reviewed
It is okay for me but just to be sure: when the author was someone else, was it because you moved it here? Maybe add your name as well as an author too.

2021-01-21 12:49 UTC, pl-buiquang commented
Yes original author was someone else. Theses classes are from internal repositories.

2021-01-21 13:03 UTC, MioRtia requested changes
I think there was a small mistake in the commit :) But otherwise, it is okay for me, I am merging this once this is corrected

2021-01-21 13:03 UTC, MioRtia commented on iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/NetworkXml.java
> +import java.nio.charset.Charset;
Please delete this unused import

2021-01-22 15:20 UTC, MioRtia approved these changes

2021-01-22 15:34 UTC, merged