Add reporter on postprocessor
powsybl/powsybl-core pull request #1907
Opened 2021-11-24 10:45 UTC by colinepiloquet

Signed-off-by: Coline Piloquet <coline.piloquet@rte-france.com>

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*
No

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*
Adds reporter in the import post-processor

2021-11-26 13:10 UTC, miovd reviewed
Could you add a test? (With a mock ImportPostProcessor)

2021-12-07 15:32 UTC, flo-dup requested changes

2021-12-07 15:32 UTC, flo-dup commented on iidm/iidm-converter-api/src/test/java/com/powsybl/iidm/import_/ImportersTest.java
> +        reporter.export(sw);
It's more consistent to check the serialization, you can use `ReporterModelSerializer::write` for that.

2021-12-08 15:01 UTC, flo-dup approved these changes

2021-12-10 14:28 UTC, miovd commented
@colinepiloquet Could you add a test on `ImportPostProcessor.process(Network network, ComputationManager computationManager)`? It is the one that blocks SonarCloud

2021-12-13 14:14 UTC, miovd commented on iidm/iidm-converter-api/src/test/java/com/powsybl/iidm/import_/PostProcessorReporterTest.java
> +
Can those be private and final?

2021-12-13 14:15 UTC, miovd commented on iidm/iidm-converter-api/src/test/java/com/powsybl/iidm/import_/PostProcessorReporterTest.java
> +        Network network1 = importer1.importData(null, NetworkFactory.findDefault(), null);
I think you have to call explicitly `process(Network, ComputationManager)`

2021-12-13 15:53 UTC, merged