[WIP] Update cgmes export
powsybl/powsybl-core pull request #1949
Opened 2022-01-24 13:01 UTC by miovd

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*

**What is the current behavior?** *(You can also link to an open issue here)*

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change or deprecate an API?** *If yes, check the following:*
- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration guide has been updated in the github wiki *(What changes might users need to make in their application due to this PR?)*

**Other information**:

(if any of the questions/checkboxes don't apply, please delete them entirely)

2022-01-26 08:33 UTC, marcosmc approved these changes

2022-02-08 14:16 UTC, zamarrenolm requested changes

2022-02-08 14:16 UTC, zamarrenolm commented on cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/EquipmentExport.java
>              String geoName = network.getNameOrId();
Proposal to reduce the complexity of code, separate pieces into two small functions that could be called like:

```java
geographicalRegionIds.computeIfAbsent(geographicalRegionName(substation),
    geoName -> writeGeographicalRegion(geoName, cimNamespace, writer));
```
With this I would like to:
- encapsulate how to obtain country name from substation or network, 
- avoid declaring a `finalGeoName`.
- and move the try/catch to a separate code block.

2022-02-08 14:16 UTC, zamarrenolm commented on cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/EquipmentExport.java
> +            if (substation.hasProperty(Conversion.CGMES_PREFIX_ALIAS_PROPERTIES + "regionId")) {
Similar proposal: separate in smaller methods that are responsible for getting the `subGeographicalRegionId` and the writing of the corresponding XML element. 
Something that could be read at this level as:
```java
subGeographicalRegionIds.computeIfAbsent(subGeographicalRegionIds(substation), 
    subGeoId -> writeGeographicalRegion(...));
```

2022-02-10 08:42 UTC, merged