Improve CGMES-IIDM mapping
powsybl/powsybl-core pull request #1959
Opened 2022-01-28 13:51 UTC by miovd

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*
No

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*
Improvements

**What is the current behavior?** *(You can also link to an open issue here)*
Some inconsistencies in CGMES mapping

**What is the new behavior (if this is a feature change)?**
- Add listeners to invalidate CGMES-IIDM topology mapping when topology is modified
- Can create CGMES-IIDM mapping during CGMES import of a Bus-Branch network
- When first export, create CGMES-IIDM mapping on network for redundancy

**Does this PR introduce a breaking change or deprecate an API?** *If yes, check the following:*
No

2022-02-07 12:43 UTC, marcosmc requested changes

2022-03-03 10:47 UTC, miovd commented on cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/AbstractConductingEquipmentConversion.java
> +        if (context.config().createCgmesExportMapping()) {
You're right! Dunno why I changed that

2022-03-07 17:52 UTC, zamarrenolm approved these changes

2022-03-07 18:49 UTC, marcosmc approved these changes

2022-03-10 08:45 UTC, zamarrenolm commented
Updated the changes with the following:

Topological Node mappings are added also for b/b models (removed the `context.nodeBreaker` condition at the start of `Conversion::convert` when building the CGMES-IIDM mappings).

Sometimes we may be importing only EQ data, then we may not have a CGMES Topological Node to add to the mapping. We take this into account and avoid putting nulls in the mapping (check and log debug in `AbstractConductingEquipmentConversion::addMappingForTopologicalNode`).

When we are testing EQ export of Networks that come from CGMES source, we are re-importing only using the exported EQ file (+boundaries). When we re-import we do not need to create the IIDM-CGMES mapping: we are in fact dropping all IIDM-CGMES mapping to compare expected and actual Networks. Change in `EquipmentExportTest`. Also small refactoring in this module to clarify the operations and verifications being made.

For switches, TP export was missing the association of terminals with the corresponding Topological Nodes. New method `TopologyExport::writeSwitchesTerminals` and minor changes to clarify code.

2022-03-10 09:09 UTC, merged