Replacing Objects.equal with ==
powsybl/powsybl-core pull request #2070
Opened 2022-04-09 05:45 UTC by bapan25

Signed-off-by: lazycoderextreme <ruptam25@gmail.com>

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*

**What is the current behavior?** *(You can also link to an open issue here)*

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change or deprecate an API?** *If yes, check the following:*
- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration guide has been updated in the github wiki *(What changes might users need to make in their application due to this PR?)*

**Other information**:

(if any of the questions/checkboxes don't apply, please delete them entirely)

2022-04-11 10:30 UTC, miovd approved these changes

2022-04-11 10:31 UTC, miovd requested changes

2022-04-11 10:31 UTC, miovd commented on iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/util/IidmXmlUtil.java
> +        writeAttributeFromMinimumVersion(rootElementName, attributeName, value != defaultValue, type,
Should not be changed for `double`

2022-04-11 10:43 UTC, geofjamg commented
what would be the impact on network store as we most of the time recreate subobjects at each access?

2022-04-11 10:52 UTC, miovd commented
> what would be the impact on network store as we most of the time recreate subobjects at each access?

@geofjamg Do you override the `equals` method in network-store implementation? If yes, this would indeed create issues...

2022-04-11 10:56 UTC, geofjamg commented
> > what would be the impact on network store as we most of the time recreate subobjects at each access?
> 
> @geofjamg Do you override the `equals` method in network-store implementation? If yes, this would indeed create issues...

No, indeed should be ok woth network store

2022-04-11 14:39 UTC, bapan25 commented on iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/util/IidmXmlUtil.java
> +        writeAttributeFromMinimumVersion(rootElementName, attributeName, value != defaultValue, type,
done

2022-04-12 09:22 UTC, miovd approved these changes

2022-04-12 13:09 UTC, merged