CGMES export: do not export terminals of fictitious equipment
powsybl/powsybl-core pull request #2111
Opened 2022-05-09 16:08 UTC by zamarrenolm

Signed-off-by: Luma <zamarrenolm@aia.es>

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [X] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*
Equipment labelled as fictitious should not be considered for export to CGMES EQ, SSH or TP instance files. No terminals should be created or written for them.

**What is the current behavior?** *(You can also link to an open issue here)*
CGMES SvInjection objects are mapped to IIDM fictitious loads. They do not have a CGMES terminal. Export fails when these loads are written in CGMES export.

**What is the new behavior (if this is a feature change)?**
Fictitious IIDM equipment are ignored when exporting terminals to CGMES.

**Does this PR introduce a breaking change or deprecate an API?** *If yes, check the following:*
- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration guide has been updated in the github wiki *(What changes might users need to make in their application due to this PR?)*

**Other information**:

(if any of the questions/checkboxes don't apply, please delete them entirely)

2022-05-10 08:49 UTC, marcosmc approved these changes

2022-05-12 08:15 UTC, miovd requested changes
I do not agree with this as it can disturb export from scratch of IIDM network containing fictitious components...

2022-05-12 08:21 UTC, zamarrenolm commented
> I do not agree with this as it can disturb export from scratch of IIDM network containing fictitious components... It should only ignore mapping of fictitious **loads** for me (that can be mapped as `SvInjection`)

Totally agree. I am rewriting it and solving the issues left with SvInjections (they were exported as equipment, that I don't like).

2022-05-17 13:54 UTC, miovd requested changes

2022-05-17 14:23 UTC, zamarrenolm commented on cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportContext.java
> -            // An fictitious load do not need an alias
`addIidmMappingsTerminal` is called (from `addIidmMappingsTerminals`) only if the equipment is exported, so this additional condition here was duplicated and I found it confusing.

2022-05-19 07:42 UTC, miovd approved these changes

2022-05-19 08:30 UTC, merged