[WIP] Allow to create feeder bays in a bus-breaker voltage level
powsybl/powsybl-core pull request #2355
Opened 2022-11-08 11:27 UTC by miovd

Signed-off-by: VEDELAGO MIORA <miora.ralambotiana@rte-france.com>

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*
No

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*
Feature: allow to use modifications to create feeder bays in a bus-breaker voltage level.

**What is the current behavior?** *(You can also link to an open issue here)*
Modifications to create feeder bays only work in node-breaker voltage levels.

**Does this PR introduce a breaking change or deprecate an API?** *If yes, check the following:*
Yes, deprecation
- [x] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration guide has been updated in the github wiki *(What changes might users need to make in their application due to this PR?)*

**Other information**:

(if any of the questions/checkboxes don't apply, please delete them entirely)

2022-11-30 15:49 UTC, flo-dup requested changes

2022-11-30 15:49 UTC, flo-dup commented on iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/ModificationReports.java
> +                .withValue(voltageLevelId, voltageLevelId)
```suggestion
                .withValue(VOLTAGE_LEVEL_ID, voltageLevelId)
```

2022-11-30 15:49 UTC, flo-dup commented on iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/ModificationReports.java
> +                .withDefaultMessage("Cannot remove feeder bay for connectable ${busbarSectionConnectableId}, as it is a busbarSection")
```suggestion
                .withDefaultMessage("Cannot remove feeder bay for connectable ${connectableId}, as it is a busbarSection")
```

2022-11-30 15:49 UTC, flo-dup commented on iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/AbstractCreateConnectableFeederBays.java
> +        createExtensionAndTopology(connectable, network, reporter);
it's clearer that way!

2022-12-01 09:52 UTC, flo-dup approved these changes

2022-12-05 09:29 UTC, miovd commented on iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/AbstractCreateConnectableFeederBays.java
> +                continue; // no extension nor switches created in bus-breaker topology
Add log message if position not null and are ignored

2022-12-05 10:37 UTC, annetill approved these changes

2022-12-05 10:44 UTC, flo-dup approved these changes

2022-12-05 11:26 UTC, merged