[WIP] change participationFactor from property to extension
powsybl/powsybl-core pull request #2435
Opened 2023-01-06 15:02 UTC by caioluke

change participationFactor from property to extension

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*

**What is the current behavior?** *(You can also link to an open issue here)*

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change or deprecate an API?** *If yes, check the following:*
- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration guide has been updated in the github wiki *(What changes might users need to make in their application due to this PR?)*

**Other information**:

(if any of the questions/checkboxes don't apply, please delete them entirely)

2023-01-06 15:13 UTC, jeandemanged requested changes

2023-01-06 15:13 UTC, jeandemanged commented on cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/SteadyStateHypothesisExport.java
> +        if (g.hasProperty(GENERATING_UNIT_PROPERTY) && !Objects.equals(g.getExtension(ActivePowerControlAdder.class), null)) {
don't use adder here, only ActivePowerControl.class

`&& (g.getExtension(ActivePowerControl.class) != null)`

2023-01-06 15:13 UTC, jeandemanged commented on cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/SteadyStateHypothesisExport.java
> +        double droop;
you can remove this, not used

2023-01-06 15:13 UTC, jeandemanged commented on iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/ActivePowerControlAdder.java
> +    double getParticipationFactor();
to remove, you did this because of the incorrect g.getExtension(ActivePowerControl**Adder**.class) above

2023-01-06 15:13 UTC, jeandemanged commented on iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/ActivePowerControlAdderImpl.java
> +    }
to remove, you did this because of the incorrect g.getExtension(ActivePowerControlAdder.class) above

2023-01-06 16:12 UTC, jeandemanged approved these changes

2023-01-09 09:12 UTC, miovd commented on cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/SynchronousMachineConversion.java
> +                    .withDroop(4.0)
You can not fill droop, it will be handled later in loadflow processing

2023-01-09 09:12 UTC, miovd requested changes
See comment

2023-01-09 11:52 UTC, annetill approved these changes

2023-01-09 11:54 UTC, jeandemanged requested changes
must change droop attribute to optional in iidm/iidm-xml-converter/src/main/resources/xsd/activePowerControl_V1_1.xsd

2023-01-09 12:22 UTC, jeandemanged approved these changes

2023-01-09 12:35 UTC, miovd commented
> must change droop attribute to optional in iidm/iidm-xml-converter/src/main/resources/xsd/activePowerControl_V1_1.xsd

Indeed. I will submit a PR about it.

2023-01-09 12:40 UTC, miovd approved these changes

2023-01-10 09:34 UTC, zamarrenolm approved these changes
Maybe we could add a test that checks that the extension has been correctly created.

For CGMES 3, in addition to the `normalPF` expressed in the SSH profile, we could have `shortPF` and `longPF` in the EQ. The descriptions of the new attributes are:

`longPF`: _Generating unit long term economic participation factor._
`shortPF`: _Generating unit short term economic participation factor._

2023-01-10 11:49 UTC, jeandemanged commented
@zamarrenolm the correct ActivePowerControl extension creation is done somewhat indirectly through the tests in SteadyStateHypothesisExportTest

Regarding shortPF and longPF, yes, and this also exists in CGMES 2.4.15. In #2402 it was decided that ActivePowerControl would handle only one participation factor. Managing these other participation factors would be best done in a dedicated CGMES iIDM extension. This is not in scope of this PR but definitely something to do for a future release train.

2023-01-11 12:40 UTC, jeandemanged commented
@miovd not sure about the need to bump a new version 1.2 of active power control extension here, because v1.1 was initiated during powsybl-core 5.1.0 development and has never been released yet

2023-01-11 13:14 UTC, merged