Add secondary voltage control IIDM extension
powsybl/powsybl-core pull request #2436
Opened 2023-01-07 20:15 UTC by geofjamg

Signed-off-by: Geoffroy Jamgotchian <geoffroy.jamgotchian@gmail.com>

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*

**What is the current behavior?** *(You can also link to an open issue here)*

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change or deprecate an API?** *If yes, check the following:*
- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration guide has been updated in the github wiki *(What changes might users need to make in their application due to this PR?)*

**Other information**:

(if any of the questions/checkboxes don't apply, please delete them entirely)

2023-01-09 09:59 UTC, annetill requested changes
After a talk with one of our colleagues (Vincent), it could be nice to associate a `boolean` to each generator (or VSC or SVC) to say that the participation is active or not.

2023-01-10 08:11 UTC, geofjamg commented on iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/SecondaryVoltageControl.java
> +        public List<String> getBusbarSectionsOrBusesIds() {
We define an ordered list of pilot point because some could be disconnected and so we need a list of busbar section fallback.

2023-01-10 08:12 UTC, geofjamg commented on iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/SecondaryVoltageControl.java
> +    class Zone {
This is correct. Googling "secondary voltage control" it seems that we found a majority of "control zone" and a few "control area".

2023-01-10 08:13 UTC, geofjamg commented on iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/SecondaryVoltageControl.java
> +        private final List<String> generatorsIds;
I don't think SVC could participate. At least I don't have some in my data.

2023-01-10 08:15 UTC, geofjamg commented on iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/SecondaryVoltageControl.java
> +        public List<String> getBusbarSectionsOrBusesIds() {
Comment added

2023-01-11 12:08 UTC, annetill approved these changes

2023-01-11 13:01 UTC, miovd reviewed
Okay with the design, I just have a few remarks. The `SPDX-License-Identifier: MPL-2.0` is also missing in the copyright disclaimer in new files.

Just as a note, the fact that IDs are stored (and not direct references) means that there is no way to check if the extension is "valid" (if the bus or busbar section has not been removed). Not a big deal though as it is true for several mechanisms in IIDM...

2023-01-11 13:52 UTC, geofjamg commented on iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/SecondaryVoltageControl.java
> +            this.controlUnits = Objects.requireNonNull(controlUnits);
```java
Objects.requireNonNull(controlUnits).forEach(Objects::requireNonNull);
this.controlUnits.addAll(controlUnits);
```

If we really want to check everything we should do that?

2023-01-11 14:07 UTC, geofjamg commented
> The `SPDX-License-Identifier: MPL-2.0` is also missing in the copyright disclaimer in new files.

Done

2023-01-11 14:13 UTC, geofjamg commented
> Just as a note, the fact that IDs are stored (and not direct references) means that there is no way to check if the extension is "valid" (if the bus or busbar section has not been removed). Not a big deal though as it is true for several mechanisms in IIDM...

yes, true. The problem is that if we design an extension we a direct link to let's say a generator, if we remove this generator, there is no way to clean the extension link and we end up with a leak and an inconsistent model.
so it is really safer to work with String id and resolve when needed. One thing that could be done is to provide utility methods into the extension API to resolve links. In that case, I thought about it but this would resulting to code with very few added value into the API so I chose to keep it into simulator.
But you are right, the consequence is that extension could be partially invalid and this is not a perfect design.

Maybe we should globally think about a way to allow extension easily been clean up when a references idetifiable is removed.

2023-01-11 14:13 UTC, geofjamg commented on iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/SecondaryVoltageControl.java
> +            this.controlUnits = Objects.requireNonNull(controlUnits);
Done

2023-01-11 14:14 UTC, geofjamg commented on iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/SecondaryVoltageControlImpl.java
> +        this.controlZones = Objects.requireNonNull(controlZones);
Done

2023-01-11 14:14 UTC, geofjamg commented on iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/SecondaryVoltageControlImpl.java
> +        return controlZones;
Done

2023-01-11 14:58 UTC, miovd requested changes

2023-01-11 14:58 UTC, miovd commented on iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/SecondaryVoltageControl.java
> +            this.controlUnits = controlUnits;
Should be changed too with `addAll`

2023-01-11 15:28 UTC, geofjamg commented on iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/SecondaryVoltageControl.java
> +            this.controlUnits = controlUnits;
Done

2023-01-11 15:59 UTC, miovd approved these changes

2023-01-12 09:10 UTC, merged