[Fix] Make reconnecting terminal optional in scalable.
powsybl/powsybl-core pull request #2461
Opened 2023-02-01 14:00 UTC by colinepiloquet

Signed-off-by: Coline PILOQUET <coline.piloquet@rte-france.com>

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [X] The commit message follows our guidelines
- [X] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*
No

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*
Bug fix: adds a boolean saying whether the terminal should be reconnected in case of scaling on a disconnected element.

**What is the current behavior?** *(You can also link to an open issue here)*
The terminal is always reconnected.

2023-02-06 10:01 UTC, annetill commented on iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/AbstractCompoundScalable.java
> -        return scale(n, asked, ScalingConvention.GENERATOR);
I don't get this change: I think you must keep the convention and add a default behavior for reconnection. @phiedw I think that reconnection should not be the default behavior, what is you opinion? Why do you need a reconnection in capacity calculation?

2023-03-13 08:52 UTC, geofjamg requested changes

2023-03-13 08:52 UTC, geofjamg commented on iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/DanglingLineScalable.java
> +    public double scale(Network n, double asked, Scalable.ScalingConvention scalingConvention, boolean reconnect) {
We really should consider grouping all theses parameters in a ScalingContext object.

2023-03-13 22:32 UTC, geofjamg commented on iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/DanglingLineScalable.java
> +    public double scale(Network n, double asked, ScalingContext context) {
If we just add read only data in `ScalingContext`, it is not really a context. It is more a `ScalingParameter`

2023-03-14 15:31 UTC, geofjamg approved these changes

2023-03-15 09:52 UTC, miovd approved these changes

2023-03-15 13:25 UTC, flo-dup approved these changes
Nice, just a tiny javadoc comment!

2023-03-15 13:42 UTC, phiedw approved these changes

2023-03-15 13:44 UTC, merged