Refactoring XML IIDM serialization classes
powsybl/powsybl-core pull request #2481
Opened 2023-03-01 14:38 UTC by miovd

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*

**What is the current behavior?** *(You can also link to an open issue here)*

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change or deprecate an API?** *If yes, check the following:*
- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration guide has been updated in the github wiki *(What changes might users need to make in their application due to this PR?)*

**Other information**:

(if any of the questions/checkboxes don't apply, please delete them entirely)

2023-03-13 15:38 UTC, flo-dup requested changes

2023-03-13 15:38 UTC, flo-dup commented on iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/AliasesXml.java
> +        toApply.add(identifiable -> identifiable.addAlias(alias, aliasType[0]));
If we don't factorize `getSubElements`, we could factorize this with a method returning `identifiable -> identifiable.addAlias(alias, aliasType[0])`, which is then applied or not.

2023-03-13 15:40 UTC, flo-dup commented on iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/AbstractComplexIdentifiableXml.java
> +    public final void read(Supplier<A> createAdder, Function<A, T> create, NetworkXmlReaderContext context) throws XMLStreamException {
I forgot the `Function<A, T> create` which is needed. We could do the same, that is, an abstract method which returns the adder. Or, better! in fact we could write `adder.add()` as I'd really like to add `add` methods in the `Adder`s

2023-03-14 09:07 UTC, miovd commented on iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/AbstractComplexIdentifiableXml.java
> +    protected void readSubElements(String id, A adder, List<Consumer<T>> toApply, NetworkXmlReaderContext context) throws XMLStreamException {
I named the methods the same but made `readSubElements` abstract

2023-03-14 09:08 UTC, miovd commented on iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/AbstractComplexIdentifiableXml.java
> +    public final void read(Supplier<A> createAdder, Function<A, T> create, NetworkXmlReaderContext context) throws XMLStreamException {
In this PR, if your change in IIDM network is not passed, I will create an abstract method to add but I'm keeping it in mind!

2023-03-14 10:41 UTC, flo-dup approved these changes

2023-03-14 10:52 UTC, merged