CGMES import: import TATL shortName or name, not ID + CGMES export: fix on LoadingLimitType and LoadingLimit names
powsybl/powsybl-core pull request #2537
Opened 2023-04-11 08:47 UTC by miovd

**Please check if the PR fulfills these requirements**

- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**

No

**What kind of change does this PR introduce?**

Bug fix/enhancement on limits naming during CGMES import/export

**Does this PR introduce a breaking change or deprecate an API?**

No

**Other information**:

2023-04-12 10:49 UTC, annetill requested changes
You must find a way to keep original ids (with alias) in order to export a CGMES file that comes from a CGMES file. It seems that there are lost.

2023-04-12 12:15 UTC, miovd commented
> You must find a way to keep original ids (with alias) in order to export a CGMES file that comes from a CGMES file. It seems that there are lost.

There were already lost but it does not seem to me that they are supposed to be persistent (same things for OperationalLimitSet)

2023-04-13 08:09 UTC, zamarrenolm approved these changes

2023-04-14 13:36 UTC, annetill approved these changes

2023-04-17 08:24 UTC, merged