[Network modifications] Add check on order position value in CreateConnectableBay
powsybl/powsybl-core pull request #2576
Opened 2023-05-17 17:11 UTC by colinepiloquet

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**

Fixes https://github.com/powsybl/powsybl-core/pull/2532.

**What kind of change does this PR introduce?**
Fix

**What is the current behavior?**
Order position value is not checked, meaning that a value that is too low or too big can be given and as long as it is not equal to an order position that is not taken, the extension will be created. After creation of the extension, the methods getUnusedOrderPositionsAfter and getUnusedOrderPositionsBefore return an empty range.

**What is the new behavior (if this is a feature change)?**
The value of the order position given as an attribute is checked and if it is wrong, the connectable is created but not the extension (same behaviour as if the order position is already taken). This check fails if the order position is negative, if it is higher than the lowest order position on the next slice or if it is slower than the highest order position in the previous slice.

2023-05-22 10:14 UTC, annetill commented on iidm/iidm-modification/pom.xml
> +        <dependency>
to be removed.

2023-05-24 11:20 UTC, flo-dup requested changes

2023-05-24 11:20 UTC, flo-dup commented on iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/AbstractCreateConnectableFeederBays.java
> +            Optional<Range<Integer>> unusedOrderPositionsBefore = getUnusedOrderPositionsBefore(busbarSection);
Here you get a range whereas you only need one of the two values. And calling the two methods makes you calculating the map of position twice. We could avoid this by calculating directly the desired values.

2023-05-24 11:20 UTC, flo-dup commented on iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/TopologyModificationUtils.java
> +        BusbarSectionPosition busbarSectionPosition = bbs.getExtension(BusbarSectionPosition.class);
Duplicate code, we can factorize this

2023-05-24 14:50 UTC, flo-dup commented on iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/CreateFeederBay.java
> +        this.injectionPositionOrder = checkPositionOrderPositive(injectionPositionOrder);
and if injectionPositionOrder is null it will throw a NPE when casting to int

2023-05-25 15:40 UTC, flo-dup approved these changes

2023-05-25 15:43 UTC, merged