Traversal from terminal by depth or breadth first
powsybl/powsybl-core pull request #2626
Opened 2023-06-26 13:28 UTC by FranckLecuyer

**Please check if the PR fulfills these requirements**

- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**

**What kind of change does this PR introduce?**

Feature

**What is the current behavior?**

The traversal from a terminal is only done by depth first

**What is the new behavior (if this is a feature change)?**
The traversal from a terminal can now be done by depth or breadth first

**Does this PR introduce a breaking change or deprecate an API?**

- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration guide has been updated in the github wiki *(What changes might users need to make in their application due to this PR?)*

**Other information**:

2023-08-09 07:32 UTC, olperr1 requested changes

2023-08-10 09:10 UTC, FranckLecuyer commented on math/src/main/java/com/powsybl/math/graph/TraversalType.java
> + */
Fixed

2023-08-10 09:10 UTC, FranckLecuyer commented on math/src/main/java/com/powsybl/math/graph/UndirectedGraphImpl.java
> +        if (traversalType == TraversalType.DEPTH_FIRST) {  // traversal by depth first
Changed

2023-08-10 09:10 UTC, FranckLecuyer commented on math/src/main/java/com/powsybl/math/graph/UndirectedGraphImpl.java
> +                vertexToTraverse.poll();
Changed

2023-08-22 08:16 UTC, olperr1 approved these changes

2023-08-29 15:04 UTC, merged