Add parameter for ModelDescription
powsybl/powsybl-core pull request #2628
Opened 2023-06-27 14:14 UTC by colinepiloquet

**Please check if the PR fulfills these requirements**

- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**

No

**What kind of change does this PR introduce?**

Bug fix

**What is the current behavior?**

Model description is the name of the file

**What is the new behavior (if this is a feature change)?**
Add possibility to put custom ModelDescription in CGMES files header. Thus it is possible to put a modelDescription fitting format expected in QoCDC.

2023-07-03 10:28 UTC, zamarrenolm requested changes

2023-07-03 10:28 UTC, zamarrenolm commented on cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesExport.java
>      private static final List<Parameter> STATIC_PARAMETERS = List.of(
the new parameter `MODEL_DESCRIPTION_PARAMETER` should be added to the list of parameters, `STATIC_PARAMETERS`.

2023-07-04 10:41 UTC, zamarrenolm approved these changes

2023-07-05 10:45 UTC, geofjamg commented on cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/CgmesExportTest.java
> +        FileSystem fileSystem = Jimfs.newFileSystem(Configuration.unix());
Don't forget to close the fs :
```java
try (FileSystem fileSystem = Jimfs.newFileSystem(Configuration.unix())) {
   ....
}
```

2023-07-05 18:26 UTC, annetill approved these changes

2023-07-06 06:03 UTC, merged