Tie line: improve remove method
powsybl/powsybl-core pull request #2647
Opened 2023-07-12 12:49 UTC by annetill

**Please check if the PR fulfills these requirements**

- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**

No.

**What kind of change does this PR introduce?**

When a tie line is removed, the underlying dangling lines `P0` and `Q0` can be updated or not. 

**What is the current behavior?**

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change or deprecate an API?**

- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration guide has been updated in the github wiki *(What changes might users need to make in their application due to this PR?)*

**Other information**:

2023-07-12 13:35 UTC, zamarrenolm requested changes

2023-07-12 13:35 UTC, zamarrenolm commented on iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/TieLineImpl.java
> +            danglingLine1.setP0(danglingLine1.getBoundary().getP());
There should be a change in sign. It should be `setP0(-danglingLine1.getBoundary().getP())` (you can check it looking at `DanglingLineBoundaryImpl.java::getP`). `P0, Q0` is a load (consumption) located at the boundary node, and `boundary.getP` is interpreted as the flow of the line seen at the boundary terminal.

2023-07-12 13:35 UTC, zamarrenolm commented on iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractTieLineTest.java
> +        assertEquals(-301.316, line1.getDanglingLine1().getP0(), 0.001);
Signs of the expected values must be updated according to the change in the implementation.

2023-07-12 13:57 UTC, zamarrenolm commented
Additionally, we could take into account the generation defined at the dangling line, keeping its targets and assigning the remainder to `(p0, q0)`. OR, simply resetting them (`targetP, targetQ` of `danglineLine.getGeneration()`).

The generation part of the dangling line only makes sense when the dangling line is not paired (not inside a tie line), to simulate the fact that the boundary at that point has support for voltage. When the dangling line is paired, its generation should be ignored for calculations, because the "other" part of the network is already modelled in detail.

When we remove tie lines and update its inner dangling lines, we could try keep the same "setpoints" that we had originally, or reset them (and let the user further update them as needed).

2023-07-13 08:07 UTC, zamarrenolm approved these changes

2023-07-13 08:09 UTC, marqueslanauja approved these changes

2023-07-13 08:43 UTC, marqueslanauja approved these changes

2023-07-13 10:02 UTC, marqueslanauja approved these changes

2023-07-17 08:32 UTC, merged