add getBusCount() to network and voltage level busbreakerview for symetry
powsybl/powsybl-core pull request #2660
Opened 2023-08-02 15:37 UTC by jonenst

**Please check if the PR fulfills these requirements**

- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**
NO

**What kind of change does this PR introduce?**
Feature

**What is the current behavior?**
no getBusCount(), but in all other places where we have a getXStream() we also have getXCount()

**What is the new behavior (if this is a feature change)?**
add getBusCount in network and voltagelevel busbreakerview

**Does this PR introduce a breaking change or deprecate an API?**
no

**Other information**:
another PR to follow, getBusCount on the busview

2023-08-07 06:37 UTC, olperr1 requested changes

2023-08-07 06:37 UTC, olperr1 commented on iidm/iidm-api/src/main/java/com/powsybl/iidm/network/Network.java
> +        }
To be consistent with the other `getXxxCount()` methods in this interface, we should not propose a default implementation. This way the existing Network's implementation's developers will be aware of the existence of this new method and could provide a more performant implementation.

2023-08-07 06:37 UTC, olperr1 commented on iidm/iidm-api/src/main/java/com/powsybl/iidm/network/VoltageLevel.java
> +        }
Same comment as for `Network.getBusCount()`.

2023-08-28 13:17 UTC, olperr1 approved these changes

2023-09-05 07:50 UTC, geofjamg approved these changes

2023-09-05 08:28 UTC, merged