Proposition for range voltage.
powsybl/powsybl-core pull request #2728
Opened 2023-10-02 12:31 UTC by colinepiloquet

**Please check if the PR fulfills these requirements**

- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**

**What kind of change does this PR introduce?**

**What is the current behavior?**

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change or deprecate an API?**

- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration guide has been updated in the github wiki *(What changes might users need to make in their application due to this PR?)*

**Other information**:

2023-10-02 12:44 UTC, colinepiloquet commented
@annetill, @olperr1 a suggestion for voltage in the voltageRange. If you validate, I also add it in FaultParameters + finish coding.

2023-10-24 13:32 UTC, olperr1 commented
> @annetill, @olperr1 a suggestion for voltage in the voltageRange. If you validate, I also add it in FaultParameters + finish coding.

It's OK for me. It's maybe the clearest thing we can have.

With this method, we can no more define a coefficient for [0 ; 230] (range which has several values for `voltage`) in a single range, but I think it's for the best since it will also highlight problematic cases where the coefficient has several values for a single value of `voltage`.

2023-11-30 16:00 UTC, olperr1 requested changes

2023-12-05 11:14 UTC, olperr1 commented on shortcircuit-api/src/main/java/com/powsybl/shortcircuit/json/VoltageRangeDeserializer.java
> +                case "voltage" -> {
You could use the following methods :
- `JsonUtil.setSourceVersion(…)`: to store the version number in the deserialization context (in `FaultParametersDeserializer` and in `ShortCircuitParametersDeserializer`);
- `Json.getSourceVersion(…)`: to retrieve it (in `VoltageRangeDeserializer`).

2023-12-05 11:36 UTC, colinepiloquet commented on shortcircuit-api/src/main/java/com/powsybl/shortcircuit/json/VoltageRangeDeserializer.java
> +                case "voltage" -> {
This is really great!! I didn't know it existed, I should have used it for other deserializers (it goes into my todo list)

2023-12-05 15:47 UTC, olperr1 approved these changes

2023-12-05 16:00 UTC, merged