CGMES. Clean up logs related to regulating controls
powsybl/powsybl-core pull request #2752
Opened 2023-10-19 10:01 UTC by zamarrenolm

**Please check if the PR fulfills these requirements**

- [X] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?**

Minor improvement

**What is the current behavior?**

Log warning messages are reported for equipment without associated regulating control objects.

**What is the new behavior (if this is a feature change)?**

Generators, shunt compensators, static var compensators and tap changers may not have an associated regulating control. We do not need to report this as "missing" data in input CGMES files.
Log messages have been kept, but the log level has been reduced to the lowest one (`TRACE`) and completed with the identifier of the equipment.

**Does this PR introduce a breaking change or deprecate an API?**

- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration guide has been updated in the github wiki *(What changes might users need to make in their application due to this PR?)*

**Other information**:

2023-11-02 14:08 UTC, annetill commented on cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/RegulatingControlMappingForShuntCompensators.java
> +            // No need to report as missing, just log a message
Can you remove both comment "// No need to report as missing, just log a message". If you are sure about the solution, you don't need a comment.

2023-11-02 14:08 UTC, annetill commented on cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/RegulatingControlMappingForGenerators.java
> +            // No need to report as missing, just log a message
To be removed too.

2023-11-02 15:25 UTC, zamarrenolm commented on cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/RegulatingControlMappingForGenerators.java
> +            // No need to report as missing, just log a message
removed

2023-11-02 15:51 UTC, annetill requested changes

2023-11-02 15:51 UTC, annetill commented on cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/RegulatingControlMappingForStaticVarCompensators.java
> +            // No need to report as missing, just log a message
Here too.

2023-11-02 15:51 UTC, annetill commented on cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/RegulatingControlMappingForTransformers.java
> +            // A tap changer may not have an associated tap changer control,
Here too.

2023-11-03 08:48 UTC, zamarrenolm commented on cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/RegulatingControlMappingForStaticVarCompensators.java
> +            // No need to report as missing, just log a message
comment removed

2023-11-03 08:50 UTC, zamarrenolm commented on cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/RegulatingControlMappingForTransformers.java
> +            // A tap changer may not have an associated tap changer control,
comment removed

2023-11-03 08:58 UTC, annetill commented on cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/EquivalentInjectionConversion.java
> +            // No need to report as missing, just log a message
Here too :-)

2023-11-03 12:21 UTC, annetill approved these changes

2023-11-03 12:39 UTC, merged