WIP: add currents limits set 1 for now, api and implem can be discuss
powsybl/powsybl-core pull request #2802
Opened 2023-11-27 17:20 UTC by pjeanmarie

**Please check if the PR fulfills these requirements**

- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**

**What kind of change does this PR introduce?**

**What is the current behavior?**

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change or deprecate an API?**
- [ ] Yes
- [ ] No

**If yes, please check if the following requirements are fulfilled**

- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration steps are described in the following section

**What changes might users need to make in their application due to this PR? (migration steps)**

**Other information**:

2023-12-04 09:52 UTC, pjeanmarie commented
Au niveau de l'adder, pour info:
newLimits(<id>) de newCurrentLimitsSet1() est équivalent en fonctionnement au beginTemporaryLimit() et addToSet() est équivalent à  endTemporaryLimit()
bien sûr les noms (entre autre) peuvent être changés

2023-12-04 10:19 UTC, pjeanmarie commented on iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractCurrentLimitsTest.java
> +        l.newCurrentLimitsSet2().newLimits("1").setPermanentLimit(700.0).addToSet().enable("1").add();
newLimits(<id>) in an OperationalLimitsSet will be added in addition to the newLimits(<id>) in the OperationalLimitsSetAdder for this use case

2023-12-04 15:02 UTC, pjeanmarie commented
@geofjamg @annetill Je vais changer l'héritage dans la mesure où LoadingLimits et son Adder ne vont plus étendre OperationalLimits et son Adder mais c'est le Set qui va les étendre, c'est ok ou ça casse qqch d'important?

2024-01-05 07:53 UTC, annetill commented on iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/OperationalLimitsGroups.java
> +public interface OperationalLimitsGroups {
Should be in the API, no?

2024-01-11 13:45 UTC, flo-dup submitted a review, later dismissed

2024-01-11 13:45 UTC, flo-dup commented on iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/FlowsLimitsDefaultHolder1.java
> +interface FlowsLimitsDefaultHolder1 extends FlowsLimitsHolder1 {
This should be an abstract class, not an interface

2024-01-11 13:45 UTC, flo-dup commented on iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/ActivePowerLimitsAndGroupAdderImpl.java
> + */
authorship is missing on the new files

2024-01-18 10:04 UTC, olperr1 requested changes

2024-01-19 09:18 UTC, olperr1 commented on iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/OperationalLimitsGroupsImpl.java
> +    }
Fixed

2024-01-19 09:38 UTC, merged