[WIP] New "Ground" indentifiable
powsybl/powsybl-core pull request #2837
Opened 2023-12-18 15:43 UTC by rolnico

**Please check if the PR fulfills these requirements**

- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**
https://github.com/powsybl/powsybl-core/issues/1131
But, in fact, ground disconnectors are not ignored but classified as disconnectors.

**What kind of change does this PR introduce?**
Bug fix / feature

**What is the current behavior?**
No distinction is made between ground disconnectors and disconnectors in IIDM and no ground element exists

**What is the new behavior (if this is a feature change)?**
A new Ground identifiable is created and can be added next to a disconnector to modelise a "ground disconnector"

**Does this PR introduce a breaking change or deprecate an API?**
- [ ] Yes
- [ ] No

**If yes, please check if the following requirements are fulfilled**

- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration steps are described in the following section

**What changes might users need to make in their application due to this PR? (migration steps)**

**Other information**:

2024-01-10 12:51 UTC, So-Fras requested changes
Thnak you for this PR.
I left 2 minor remarks.
In order to make the examples in tests more realistic, the disconnectors (or the bus in bus-breaker view) associated with the grounds could be linked with a line.

2024-01-10 12:51 UTC, So-Fras commented on iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractGroundTest.java
> +    public void initNetwork() {
It looks like this network is a duplicate of the network created in `GroundSerDeTest`, at least if we omit the ground and the associated disconnector parts. If it is indeed the case, could it be possible to factorize this code in the iidm-test package?

2024-01-10 15:36 UTC, So-Fras commented
I am thinking about something: should we allow the ground creation in bus/breaker view? Will the associated disconnector be present on a bus/breaker network?

2024-01-11 14:40 UTC, flo-dup requested changes

2024-01-11 14:40 UTC, flo-dup commented on iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NodeBreakerVoltageLevel.java
> +                        case LOAD, GENERATOR, BATTERY, SHUNT_COMPENSATOR, STATIC_VAR_COMPENSATOR, GROUND -> feederCount++;
adding the ground here means that the following cases are considered as a valid bus:
- a busbar with a ground
- a line and two grounds

I think we don't want that

2024-01-15 11:24 UTC, flo-dup approved these changes

2024-01-15 12:27 UTC, So-Fras approved these changes

2024-01-15 13:26 UTC, flo-dup requested changes
Just realized we forgot to put it in TopologyVisitor!

2024-01-15 14:59 UTC, flo-dup approved these changes

2024-01-15 15:58 UTC, merged