CGMES ground conversion: minimize unit test file
powsybl/powsybl-core pull request #2857
Opened 2024-01-17 17:10 UTC by zamarrenolm

**Please check if the PR fulfills these requirements**

- [X] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?**

Update unit test resource.

**What is the new behavior (if this is a feature change)?**
The unit test for CGMES conversion of cim:Ground objects has been reduced to a minimum size.
Only the required objects have been left in the CGMES EQ file.
It contains two `Ground` objects with their corresponding `GroundDisconnector`s. One is declared as normally open, the other is declared as normally closed:
<img width="385" alt="Screenshot 2024-01-17 at 18 03 33" src="https://github.com/powsybl/powsybl-core/assets/3374819/fec2f0bb-75b9-47e2-8d4d-1e4fbd13adda">

**Does this PR introduce a breaking change or deprecate an API?**
- [ ] Yes
- [X] No

2024-01-17 17:38 UTC, annetill approved these changes

2024-01-18 08:57 UTC, olperr1 commented
@zamarrenolm:
Can you also add a generator?
The `GroundConversionTest` checks one of the grounds' connectivity state. It is disturbing to see that the ground is not connected while its breaker is closed (no bus is detected as there's no feeder; adding a generator will change that).

Can you also modify the test to check the connectivity state of both `Ground` objects?

2024-01-18 12:24 UTC, So-Fras requested changes

2024-01-18 12:24 UTC, So-Fras commented on cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/GroundConversionTest.java
> +        assertNotNull(groundOU);
This line is repeated just below.

2024-01-18 12:26 UTC, zamarrenolm commented on cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/GroundConversionTest.java
> +        assertNotNull(groundOU);
fixed

2024-01-18 12:26 UTC, So-Fras approved these changes

2024-01-18 12:50 UTC, So-Fras approved these changes

2024-01-18 12:55 UTC, olperr1 approved these changes

2024-01-18 13:01 UTC, merged

2024-01-18 13:03 UTC, olperr1 commented
@zamarrenolm: Thank you!