[ShortCircuit] Corrections in javadoc
powsybl/powsybl-core pull request #2894
Opened 2024-02-07 15:27 UTC by colinepiloquet

**Please check if the PR fulfills these requirements**

- [x] The commit message follows our guidelines
- [x] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**

No

**What kind of change does this PR introduce?**

Docs update

**What is the current behavior?**

It is unclear when shortcircuit, short circuit and short-circuit is used.

**What is the new behavior (if this is a feature change)?**
I tried to make the English as correct as possible in the javadoc. ONLY modifications to the javadoc should be done.

**Does this PR introduce a breaking change or deprecate an API?**
- [ ] Yes
- [x] No

2024-02-07 15:59 UTC, So-Fras requested changes
I suggested some changes regarding the short-circuit / short circuit use. Tell me if you agree!

As for measures/measurements, I am not 100% confident. In PowSyBl, we do use "measurement"...

2024-02-07 15:59 UTC, So-Fras commented on shortcircuit-api/src/main/java/com/powsybl/shortcircuit/Fault.java
> + * Used for elementary short circuit analysis only.
```suggestion
 * Used for elementary short-circuit analysis only.
```

2024-02-07 15:59 UTC, So-Fras commented on shortcircuit-api/src/main/java/com/powsybl/shortcircuit/BusFault.java
> + * Used for elementary short circuit analysis only.
```suggestion
 * Used for elementary short-circuit analysis only.
```

2024-02-07 15:59 UTC, So-Fras commented on shortcircuit-api/src/main/java/com/powsybl/shortcircuit/BranchFault.java
> + * Used for elementary short circuit analysis only.
```suggestion
 * Used for elementary short-circuit analysis only.
```

2024-02-07 15:59 UTC, So-Fras commented on shortcircuit-api/src/main/java/com/powsybl/shortcircuit/AbstractFault.java
> + * Used for elementary short circuit analysis only.
```suggestion
 * Used for elementary short-circuit analysis only.
```

2024-02-07 15:59 UTC, So-Fras commented on shortcircuit-api/pom.xml
> +    <description>An API to run three-phase short circuit analysis</description>
```suggestion
    <description>An API to run three-phase short-circuit analysis</description>
```

2024-02-07 15:59 UTC, So-Fras commented on powerfactory/powerfactory-converter/src/main/java/com/powsybl/powerfactory/converter/TransformerConverter.java
> +            // calculate leakage impedance from short-circuit measures
```suggestion
            // calculate leakage impedance from short-circuit measurements
```

2024-02-08 16:33 UTC, colinepiloquet commented
> I suggested some changes regarding the short-circuit / short circuit use. Tell me if you agree!
> 
> As for measures/measurements, I am not 100% confident. In PowSyBl, we do use "measurement"...

I don't know either for measurements but I am fine with it. For some reason I had the feeling that with analysis "short circuit" was used but I looked a bit on IEC side and could not convince myself. To make it easy I would go with "short circuit" for a noun and "short-circuit' for a verb or adjective. So I followed your change requests. Thanks for reviewing that.

2024-02-09 08:49 UTC, So-Fras approved these changes

2024-02-19 08:06 UTC, annetill approved these changes

2024-02-19 08:55 UTC, merged