CGMES condensers shall not have generating units
powsybl/powsybl-core pull request #2905
Opened 2024-02-22 22:34 UTC by zamarrenolm

**Please check if the PR fulfills these requirements**

- [X] The commit message follows our guidelines
- [X] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?**

Bug fix

**What is the current behavior?**

In CGMES, all synchronous machines are expected to have an associated generating unit.

**What is the new behavior (if this is a feature change)?**
Synchronous condensers have no capability for active power output. They shall not be associated with a generating unit.
It is stated in ENTSO-E QoCDC rules. Rule: SynchronousCondenser Level: 3 Severity: ERROR.

**Does this PR introduce a breaking change or deprecate an API?**
- [X] Yes
- [ ] No

**If yes, please check if the following requirements are fulfilled**

- [X] The *Breaking Change* or *Deprecated* label has been added
- [X] The migration steps are described in the following section

**What changes might users need to make in their application due to this PR? (migration steps)**

We have deprecated the method to obtain the synchronous machines (SMs) in the `CgmesModel` class: `synchronousMachines()` , and  defined two new methods to be used from now on: `synchronousMachinesGenerators()` to get SMs that can act as generators and `synchronousMachinesCondensers()` that will return only the SMs that are of type `condenser`.

**Other information**:

The Svedala test configuration of ENTSO-E CAS v3.0.2 contains a condenser that has an associated generating unit with `minP = maxP = 0`. The QoCDC rule is not respected in this test case. The PowSyBl CGMES converter will import the condenser, ignoring the association with the generating unit.

2024-02-23 09:42 UTC, annetill commented
Note: export without GU to be compliant with QoCDC

2024-02-26 13:44 UTC, annetill approved these changes
Export must be compliant with QoCDC: no generating unit for condensers.

2024-02-27 16:43 UTC, zamarrenolm commented
> Export must be compliant with QoCDC: no generating unit for condensers.

adapted and tested the export

2024-03-04 08:40 UTC, zamarrenolm commented on cgmes/cgmes-model/src/main/resources/CIM100.sparql
> +OPTIONAL { GRAPH ?graphSSH2 {
To have the same semantics that we have in `CIM16.sparql`. Here we are just saying that SSH attributes for the synchronous machine and generating unit are not necessarily read from the same SSH instance file.

2024-03-04 15:09 UTC, rcourtier requested changes

2024-03-04 15:55 UTC, zamarrenolm commented on cgmes/cgmes-conversion/src/test/resources/issues/condenser2_EQ.xml
> +        <cim:RegulatingControl.mode rdf:resource="http://iec.ch/TC57/CIM100#RegulatingControlModeKind.voltage" />
applied the correction

2024-03-04 15:56 UTC, zamarrenolm commented on cgmes/cgmes-conversion/src/test/resources/issues/condenser2_EQ.xml
> +        <cim:SynchronousMachine.type rdf:resource="http://iec.ch/TC57/CIM100#SynchronousMachineKind.condenser" />
applied the correction

2024-03-04 15:59 UTC, rcourtier approved these changes

2024-03-05 07:32 UTC, merged