Export ActivePowerControl extension in IIDM 1.0
powsybl/powsybl-core pull request #2914
Opened 2024-02-29 12:03 UTC by colinepiloquet

**Please check if the PR fulfills these requirements**

- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**

**What kind of change does this PR introduce?**

**What is the current behavior?**

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change or deprecate an API?**
- [ ] Yes
- [ ] No

**If yes, please check if the following requirements are fulfilled**

- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration steps are described in the following section

**What changes might users need to make in their application due to this PR? (migration steps)**

**Other information**:

2024-02-29 13:43 UTC, colinepiloquet commented
I've started. I am really not sure the name of the parameter is good... And if it's the use case?

2024-03-06 09:00 UTC, flo-dup requested changes

2024-03-06 10:34 UTC, colinepiloquet commented on iidm/iidm-serde/src/main/java/com/powsybl/iidm/serde/AbstractTreeDataExporter.java
> + *         <td>if true, the ActivePowerControl extension is exported in IIDM version 1.0</td>
Do you mean through the `iidm.export.xml.extensions`? Then the user would just have to add it or not to the list of extensions to export it or not. And it does not require additional parameters or anything.

2024-03-11 09:38 UTC, flo-dup requested changes

2024-03-11 09:38 UTC, flo-dup commented on iidm/iidm-serde/src/test/java/com/powsybl/iidm/serde/extensions/ActivePowerControlXmlTest.java
> +        generator.addExtension(ActivePowerControl.class, new ActivePowerControlImpl<>(generator, false, 3.0, 1.0));
this could be put in a setup method

2024-03-11 09:38 UTC, flo-dup commented on iidm/iidm-serde/src/test/java/com/powsybl/iidm/serde/extensions/ActivePowerControlXmlTest.java
> +        assertEquals(activePowerControl.getName(), activePowerControl2.getName());
this is already contained in the roundtrip check

2024-03-11 09:38 UTC, flo-dup commented on iidm/iidm-serde/src/test/java/com/powsybl/iidm/serde/extensions/ActivePowerControlXmlTest.java
> +    void testIidmV10WithoutActivePowerControlExtension() throws IOException {
I think there's no use to test this, as this feature of excluding at export one or all extension is already tested in `ExportOptionsTest`.

2024-03-12 15:08 UTC, flo-dup reviewed
It seems ok to me! **But** I'd like to double-check with someone who knows precisely the usecase.

2024-03-15 08:17 UTC, geofjamg approved these changes

2024-03-15 09:23 UTC, merged