Add new field Name in equals and hash code
powsybl/powsybl-core pull request #2915
Opened 2024-03-04 10:21 UTC by pjeanmarie

**Please check if the PR fulfills these requirements**

- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**

**What kind of change does this PR introduce?**

**What is the current behavior?**

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change or deprecate an API?**
- [ ] Yes
- [ ] No

**If yes, please check if the following requirements are fulfilled**

- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration steps are described in the following section

**What changes might users need to make in their application due to this PR? (migration steps)**

**Other information**:

2024-03-04 12:27 UTC, EtienneLt commented on contingency/contingency-api/src/main/java/com/powsybl/contingency/Contingency.java
> +            return id.equals(other.id) && Objects.equals(name, other.name) && elements.equals(other.elements);
```java
name.equals(other.name)
```
is it not better ?

2024-03-05 13:52 UTC, annetill requested changes
Unit test missing.

2024-03-07 08:48 UTC, pjeanmarie commented on contingency/contingency-api/src/main/java/com/powsybl/contingency/Contingency.java
> +            return id.equals(other.id) && Objects.equals(name, other.name) && elements.equals(other.elements);
name can be null

2024-03-07 13:59 UTC, obrix approved these changes

2024-03-07 15:06 UTC, annetill approved these changes

2024-03-07 15:07 UTC, merged