Matpower: export dclines
powsybl/powsybl-core pull request #2932
Opened 2024-03-14 15:11 UTC by marqueslanauja

**Please check if the PR fulfills these requirements**

- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**

**What kind of change does this PR introduce?**

`Vsc HvdcLines` are exported as `dcLines`.

**What is the current behavior?**

`Vsc HvdcLines` are exported as two independent generators.

**What is the new behavior (if this is a feature change)?**

`Vsc HvdcLines` are exported as  `dcLines`
Bus numbers are preserved if the `iidm` model has been imported from `matpower`.

The `status` of the `dcLine` is imported and exported. 
Disconnected hvdcLines are exported with `status 0` if the connectable buses are inside the main component. 
This change will be extended to all equipment in a separated PR.

**Does this PR introduce a breaking change or deprecate an API?**
- [ ] Yes
- [ ] No

**If yes, please check if the following requirements are fulfilled**

- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration steps are described in the following section

**What changes might users need to make in their application due to this PR? (migration steps)**

**Other information**:

2024-05-06 07:01 UTC, geofjamg requested changes

2024-05-06 07:01 UTC, geofjamg commented on matpower/matpower-converter/src/main/java/com/powsybl/matpower/converter/MatpowerExporter.java
> +        private void obtainBusesOutsideMainSynchronousComponentToBeConsidered(Network network) {
You should better explain why you are doing all this complex topology processing. I personnally didn't understand without additionnal explanations. We have to be aware that all this processing to get synhcronous components exclusing LCC is technical debt for the code. If there is no other way to support HVDC export, why not but at least we have to document it.

2024-05-06 12:01 UTC, marqueslanauja commented on matpower/matpower-converter/src/main/java/com/powsybl/matpower/converter/MatpowerExporter.java
> +        private void obtainBusesOutsideMainSynchronousComponentToBeConsidered(Network network) {
Done

2024-05-06 12:12 UTC, marqueslanauja commented on matpower/matpower-converter/src/main/java/com/powsybl/matpower/converter/MatpowerExporter.java
> +        return busNumber.matches("[1-9]\\d*") ? OptionalInt.of(Integer.parseInt(busNumber)) : OptionalInt.empty();
Not only for roundtrip tests. In matpower models, the bus number is the only way to identify it. We preserve the original ones if the `iidm` model has been created by importing a matpower model.

2024-05-16 12:40 UTC, geofjamg approved these changes

2024-05-17 09:57 UTC, merged