Code cleanup to correct issues reported by Sonar
powsybl/powsybl-core pull request #2967
Opened 2024-04-05 14:16 UTC by rolnico

**Please check if the PR fulfills these requirements**

- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**

**What kind of change does this PR introduce?**

**What is the current behavior?**

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change or deprecate an API?**
- [ ] Yes
- [ ] No

**If yes, please check if the following requirements are fulfilled**

- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration steps are described in the following section

**What changes might users need to make in their application due to this PR? (migration steps)**

**Other information**:

2024-04-12 12:16 UTC, rolnico commented
This is the first PR, others are coming

2024-04-12 13:06 UTC, EtienneLt commented on commons/src/main/java/com/powsybl/commons/parameters/Parameter.java
> +        if (isPresent.test(value) && value != null) {
exchange the checks

2024-04-16 06:40 UTC, rolnico commented on commons/src/main/java/com/powsybl/commons/parameters/Parameter.java
> +        if (isPresent.test(value) && value != null) {
done

2024-04-23 14:01 UTC, olperr1 requested changes

2024-04-23 14:01 UTC, olperr1 commented on loadflow/loadflow-validation/src/main/java/com/powsybl/loadflow/validation/CandidateComputations.java
> +        return getComputations().stream().map(CandidateComputation::getName).toList();
Could you precise in the javadoc that the returned list is immutable… and add this same information in the `getComputations`'s one?

I think that returning an immutable list here is legitimate, but this change of behavior should be clearly stated. I will add a notice in the PR description.

2024-04-24 07:13 UTC, rolnico commented on cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/TransformerConversionTest.java
> +        return !(Math.abs(expected.p1 - actual.p1) > tol) &&
done

2024-04-24 07:16 UTC, rolnico commented on cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/TransformerConversionTest.java
>          }
done

2024-04-24 07:37 UTC, rolnico commented on commons/src/main/java/com/powsybl/commons/config/ComponentDefaultConfig.java
> +            } catch (NoSuchMethodException | InvocationTargetException e) {
done

2024-04-24 07:38 UTC, rolnico commented on commons/src/main/java/com/powsybl/commons/json/JsonUtil.java
> +        if (parser.currentToken() != com.fasterxml.jackson.core.JsonToken.START_OBJECT) {
yep, I forgot to change it

2024-04-24 07:38 UTC, rolnico commented on commons/src/main/java/com/powsybl/commons/json/JsonUtil.java
> +            com.fasterxml.jackson.core.JsonToken token = parser.currentToken();
same

2024-04-24 07:39 UTC, rolnico commented on computation/src/main/java/com/powsybl/computation/DefaultComputationManagerConfig.java
> +        } catch (InvocationTargetException | NoSuchMethodException e) {
done

2024-04-24 07:41 UTC, rolnico commented on iidm/iidm-serde/src/main/java/com/powsybl/iidm/serde/XMLImporter.java
> +    private void closeAndUseGarbageCollector(XMLStreamReader xmlStreamReader) {
ok

2024-04-24 07:42 UTC, rolnico commented on loadflow/loadflow-validation/src/main/java/com/powsybl/loadflow/validation/ValidationUtils.java
> +            throw new PowsyblException(e);
ok

2024-04-24 07:45 UTC, rolnico commented on psse/psse-converter/src/main/java/com/powsybl/psse/converter/PsseExporter.java
> +            if (Objects.requireNonNull(version.major()) == PsseVersion.Major.V35) {
ok

2024-04-24 07:55 UTC, olperr1 commented on time-series/time-series-api/src/main/java/com/powsybl/timeseries/TimeSeriesMetadata.java
> +        this(name, dataType, Collections.unmodifiableMap(new LinkedHashMap<>()), index);
Can you add a comment to ensure no-one else will inadvertently change it?

2024-04-24 12:48 UTC, olperr1 requested changes

2024-04-24 12:48 UTC, olperr1 commented on commons/src/main/java/com/powsybl/commons/exceptions/UncheckedInvocationTargetException.java
> +    }
This method should return an `InvocationTargetException`:

```suggestion
    public synchronized InvocationTargetException getCause() {
        return (InvocationTargetException) super.getCause();
    }
```

2024-04-24 12:48 UTC, olperr1 commented on commons/src/main/java/com/powsybl/commons/exceptions/UncheckedNoSuchMethodException.java
> +    }
This method should return a `NoSuchMethodException`:
```suggestion
    public synchronized NoSuchMethodException getCause() {
        return (NoSuchMethodException) super.getCause();
    }
```

2024-04-24 12:48 UTC, olperr1 commented on commons/src/test/java/com/powsybl/commons/config/ComponentDefaultConfigTest.java
> +        C(String a, String b) {}
To fix the checkstyle issue:

```suggestion
        C(String a, String b) { }
```

2024-04-24 12:48 UTC, olperr1 commented on commons/src/test/java/com/powsybl/commons/util/StringToIntMapperTest.java
> +            String expectedStr = "TYPE;value1;1\n";
This test may fail on some OS because of the `\n`. Use `System.lineSeparator()` instead.

2024-04-24 12:48 UTC, olperr1 commented on commons/src/test/java/com/powsybl/commons/util/StringToIntMapperTest.java
> +                writer.write("TYPE;value1;1\n");
Use `System.lineSeparator()` instead.

2024-04-24 12:48 UTC, olperr1 commented on commons/src/test/java/com/powsybl/commons/util/StringToIntMapperTest.java
> +                writer.write("TYPE;value1;1;5\n");
Idem, use `System.lineSeparator()` instead.

2024-04-24 13:27 UTC, merged