[WIP] Update to IIDM version 1.13
powsybl/powsybl-core pull request #2976
Opened 2024-04-12 09:27 UTC by colinepiloquet

**Please check if the PR fulfills these requirements**

- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**

**What kind of change does this PR introduce?**

**What is the current behavior?**

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change or deprecate an API?**
- [ ] Yes
- [ ] No

**If yes, please check if the following requirements are fulfilled**

- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration steps are described in the following section

**What changes might users need to make in their application due to this PR? (migration steps)**

**Other information**:

2024-05-07 14:30 UTC, olperr1 requested changes

2024-05-07 14:30 UTC, olperr1 commented on iidm/iidm-serde/src/test/resources/V1_13/eurostag-tutorial1-lf-extensions.bin
@flo-dup Shouldn't this file (and its counterparts in the other versioned directories) also be removed?

2024-05-07 14:30 UTC, olperr1 commented on iidm/iidm-serde/src/test/resources/V1_13/xsd/terminalMock.xsd
> +<xs:schema version="1.6"
This version number should also be changed:
```suggestion
<xs:schema version="1.13"
```

2024-05-07 14:30 UTC, olperr1 commented on iidm/iidm-serde/src/test/resources/xsd/terminalMockNoSerDe.xsd
>  <xs:schema version="1.6"
This version number should also be changed:
```suggestion
<xs:schema version="1.13"
```

2024-05-07 14:30 UTC, olperr1 commented on iidm/iidm-serde/src/test/resources/xsd/terminalMockNoSerDe.xsd
>             targetNamespace="http://www.powsybl.org/schema/iidm/ext/terminal_mock_no_serde/1_12"
This version number should also be changed:
```suggestion
           targetNamespace="http://www.powsybl.org/schema/iidm/ext/terminal_mock_no_serde/1_13"
```

2024-05-07 14:30 UTC, olperr1 commented on iidm/iidm-serde/src/test/resources/xsd/terminalMockNoSerDe.xsd
> +    <xs:import namespace="http://www.powsybl.org/schema/iidm/1_13" schemaLocation="iidm_V1_12.xsd"/>
This version number should also be changed:
```suggestion
    <xs:import namespace="http://www.powsybl.org/schema/iidm/1_13" schemaLocation="iidm_V1_13.xsd"/>
```

2024-05-27 11:24 UTC, colinepiloquet commented on iidm/iidm-serde/src/test/resources/V1_13/eurostag-tutorial1-lf-extensions.bin
I have removed the one in 1.13 and 1.12, I think it was the only two.

2024-05-28 10:36 UTC, olperr1 approved these changes

2024-06-19 06:57 UTC, merged