Add network modification to hvdc line action
powsybl/powsybl-core pull request #3031
Opened 2024-05-23 08:31 UTC by pjeanmarie

**Please check if the PR fulfills these requirements**

- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**

**What kind of change does this PR introduce?**

**What is the current behavior?**

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change or deprecate an API?**
- [ ] Yes
- [ ] No

**If yes, please check if the following requirements are fulfilled**

- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration steps are described in the following section

**What changes might users need to make in their application due to this PR? (migration steps)**

**Other information**:

2024-05-23 10:43 UTC, pjeanmarie commented
I have created a modification completly similar to the object HvdcAction (and sonar reports duplicate code). I can create 2 modifications one close to hvdc line object and another one for its extension.

2024-05-23 15:11 UTC, olperr1 commented
I would not split this network modification in 2.
Regarding the code duplication, are the getters necessary? A lot of network modifications don't have any.

2024-05-23 15:11 UTC, olperr1 requested changes

2024-05-27 09:55 UTC, pjeanmarie commented on iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/HvdcLineModification.java
> +        }
done

2024-05-27 09:55 UTC, pjeanmarie commented
> I would not split this network modification in 2. Regarding the code duplication, are the getters necessary? A lot of network modifications don't have any.

done

2024-05-28 07:39 UTC, annetill approved these changes

2024-05-28 08:29 UTC, olperr1 approved these changes

2024-05-28 08:37 UTC, merged