ODRE import postprocessor fixes
powsybl/powsybl-core pull request #3080
Opened 2024-06-24 09:24 UTC by flo-dup

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**
No

**What kind of change does this PR introduce?**
Cleaning post processor code

**What is the current behavior?**
- 40s on my laptop to import all the lines & substations positions
- 3 graph traversals for each line
- coordinates duplicated if same line reference twice with code_ligne_x and code_ligne_y
- code duplication
- substations read twice

**What is the new behavior (if this is a feature change)?**
- 5s on my laptop to import all the lines & substations positions
- graph not created if only one entry
- one single graph traversal for each problematic line 
- coordinates not duplicated if same line reference twice with code_ligne_x and code_ligne_y
- code factorization
- substations read once

**Does this PR introduce a breaking change or deprecate an API?**
- [ ] Yes
- [x] No

2024-06-25 07:25 UTC, olperr1 requested changes

2024-08-08 13:03 UTC, flo-dup commented on iidm/iidm-geodata/src/main/java/com/powsybl/iidm/geodata/odre/GeographicDataParser.java
> +    private static List<List<Coordinate>> fillMultipleConnectedSetsCoordinatesList(List<ConnectedSet> connectedSets,
removed

2024-08-08 13:04 UTC, flo-dup commented on iidm/iidm-geodata/src/main/java/com/powsybl/iidm/geodata/odre/GeographicDataParser.java
> +            return l1 > l2 ? coordinatesComponent1 : coordinatesComponent2;
Indeed, that was quite a mistake! fixed

2024-08-20 13:29 UTC, olperr1 requested changes
Could you also add a few comments in `GeographicDataParser` to describe briefly what the principal methods are doing? It will improve its readability.

2024-09-12 16:07 UTC, flo-dup commented on iidm/iidm-geodata/src/main/java/com/powsybl/iidm/geodata/utils/LineCoordinatesOrdering.java
> +    private static List<Coordinate> orderCoordinates(Coordinate s1, Coordinate s2, Coordinate firstCoordinate, Coordinate lastCoordinate,
done in the ternary conditional operators, but not in the if (we don't want a warn for the equality values, which are anyway very unlikely)

2024-09-12 16:13 UTC, flo-dup commented on iidm/iidm-geodata/src/main/java/com/powsybl/iidm/geodata/utils/LineCoordinatesOrdering.java
> +                return orderCoordinates(s1.get(), lastCoordinate, firstCoordinate, lineCoordinates);
Indeed!

2024-09-23 12:53 UTC, olperr1 approved these changes

2024-09-23 14:00 UTC, merged