Docs: fix bad edge 7-8 and make edges follow the underlying equipment in nodeBreakerTopologyGraph.svg
powsybl/powsybl-core pull request #3108
Opened 2024-07-24 15:47 UTC by jonenst

**Please check if the PR fulfills these requirements**

- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**

NO

**What kind of change does this PR introduce?**

Docs update

**What is the current behavior?**

hard to understand how the green edges and pink edge correspond to the underlying disconnectors/breakers

**What is the new behavior (if this is a feature change)?**
Hopefully easier to follow ?

**Does this PR introduce a breaking change or deprecate an API?**
- [ ] Yes
- [x] No

2024-07-24 15:58 UTC, jonenst commented
would it be even better with the rest of the diagonal edges following the underlying equipment ?
![nodeBreakerTopologyGraph](https://github.com/user-attachments/assets/1a6ae4d6-f22a-4ec1-a905-476b92e0b931)

2024-07-30 14:04 UTC, So-Fras requested changes
Thanks for fixing the 7-8 edge! 
There is also another mistake to fix for the 5-6 edge (it should be a dotted line). Could you fix it too?
I think that the diagonal lines are more visible. I can visualize the connections at a glance without needing to zoom in. What do you think?

2024-08-02 16:09 UTC, jonenst commented
![nodeBreakerTopologyGraph](https://github.com/user-attachments/assets/89aa80f5-16dc-4d13-8fed-df626d379f01)
better like this ? I pushed this version

2024-08-05 13:40 UTC, olperr1 approved these changes

2024-08-05 13:46 UTC, merged