Add anchors in the documentation
powsybl/powsybl-core pull request #3126
Opened 2024-09-02 10:03 UTC by colinepiloquet

**Please check if the PR fulfills these requirements**

- [X] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**

No

**What kind of change does this PR introduce?**

Docs update

**What is the current behavior?**

A lot of sections of the documentation have no anchors so they cannot be referenced to in the documentation of other repositories.

**What is the new behavior (if this is a feature change)?**
Add some anchors

2024-09-03 09:00 UTC, colinepiloquet commented
@So-Fras, there might be some missing but it's a start and it covers what I need for the tutorials for now (actually, way more). Maybe I did not choose the best names sometimes though.

2024-09-03 14:10 UTC, So-Fras requested changes
Thanks for your work!

2024-09-03 14:10 UTC, So-Fras commented on docs/grid_features/loadflow_validation.md
> +(loadflow-validation-laods)=
```suggestion
(loadflow-validation-loads)=
```

2024-09-03 16:08 UTC, colinepiloquet commented on docs/grid_features/loadflow_validation.md
> +(loadflow-validation-laods)=
Oups

2024-09-04 07:43 UTC, So-Fras approved these changes

2024-09-11 09:25 UTC, merged