Importers: network update API
powsybl/powsybl-core pull request #3148
Opened 2024-09-19 16:15 UTC by zamarrenolm

**Please check if the PR fulfills these requirements**

- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**

**What kind of change does this PR introduce?**

Feature

**What is the current behavior?**

Once a Network is created, it can not be updated with additional data acquired by Importers.

**What is the new behavior (if this is a feature change)?**
Allow Importers to update an existing Network with additional data read from external data sources.

**Does this PR introduce a breaking change or deprecate an API?**
- [ ] Yes
- [X] No

**If yes, please check if the following requirements are fulfilled**

- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration steps are described in the following section

**What changes might users need to make in their application due to this PR? (migration steps)**

**Other information**:

2024-12-12 08:58 UTC, zamarrenolm commented
Not implement all potential overloads for the Network and Importer update method.
It can be done in this same PR after an agreement on the base change is reached.

2025-02-20 11:46 UTC, zamarrenolm commented on iidm/iidm-api/src/main/java/com/powsybl/iidm/network/Importer.java
> +        update(network, dataSource, parameters);
Yes, it makes more sense. 
Just an observation: the similar default methods defined in this module for `importData` would create an infinite recursion if no implementation for one of them is provided later.

2025-02-27 08:30 UTC, rcourtier submitted a review, later dismissed

2025-05-16 12:59 UTC, olperr1 requested changes

2025-05-16 12:59 UTC, olperr1 commented on iidm/iidm-api/src/test/java/com/powsybl/iidm/network/TestImporter.java
> +                    .withMessageTemplate("test", "Update model ${model}")
Can you migrate this message to the new ReportNode v3 API?
- replace this line with
  - `.withMessageTemplate("testUpdateModel")`
- add the following line in `iidm/iidm-api/src/test/resources/i18n/reports.properties`:
  - `testUpdateModel = Update model ${model}`

2025-05-19 06:16 UTC, zamarrenolm commented on iidm/iidm-api/src/test/java/com/powsybl/iidm/network/TestImporter.java
> +                    .withMessageTemplate("test", "Update model ${model}")
Done. I've changed the call to `withMessageTemplate` to avoid a deprecation warning:

```java
reportNode.newReportNode()
        .withResourceBundles(PowsyblCoreTestReportResourceBundle.TEST_BASE_NAME)
        .withMessageTemplate("testUpdateModel")
        .withUntypedValue("model", "eurostagTutorialExample1")
        .add();
```

2025-05-19 07:41 UTC, olperr1 commented on iidm/iidm-api/src/test/java/com/powsybl/iidm/network/TestImporter.java
> +                    .withMessageTemplate("test", "Update model ${model}")
Thanks!

2025-05-19 08:06 UTC, rcourtier approved these changes

2025-05-19 08:31 UTC, merged