[CGMES GL] Add SubstationPosition extension when location on voltage levels
powsybl/powsybl-core pull request #3159
Opened 2024-09-25 21:02 UTC by flo-dup

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**
No

**What kind of change does this PR introduce?**
feature

**What is the current behavior?**
In CGMES GL import, only locations on substations PowerSystemResource are supported

**What is the new behavior (if this is a feature change)?**
In CGMES GL import, locations on substations and voltage levels PowerSystemResource are supported

**Does this PR introduce a breaking change or deprecate an API?**
- [ ] Yes
- [x] No

**Other information**:
- When several voltage level locations inside the same substation, the average latitude and longitude is computed
- When voltage level location inside a substation with location, the voltage level location is dismissed

2024-09-26 16:05 UTC, olperr1 commented on cgmes/cgmes-gl/src/test/resources/importGL_EQ.xml
> +    <cim:IdentifiedObject.name>Voltage level 1</cim:IdentifiedObject.name>
```suggestion
    <cim:IdentifiedObject.name>Voltage level 3</cim:IdentifiedObject.name>
```

2024-09-26 16:05 UTC, olperr1 commented on cgmes/cgmes-gl/src/test/resources/importGL_EQ.xml
> +    <cim:IdentifiedObject.name>Voltage level 1</cim:IdentifiedObject.name>
```suggestion
    <cim:IdentifiedObject.name>Voltage level 4</cim:IdentifiedObject.name>
```

2024-09-26 16:12 UTC, olperr1 approved these changes

2024-09-26 16:17 UTC, So-Fras requested changes

2024-09-26 16:17 UTC, So-Fras commented on cgmes/cgmes-gl/src/main/java/com/powsybl/cgmes/gl/CgmesGLModel.java
> +    public PropertyBags getSubstationsVoltageLevelsPosition() {
```suggestion
    public PropertyBags getSubstationVoltageLevelPosition() {
```

2024-09-26 16:17 UTC, So-Fras commented on cgmes/cgmes-gl/src/main/java/com/powsybl/cgmes/gl/CgmesGLModel.java
> +        LOG.info("Querying triple store for substations and voltage levels positions");
```suggestion
        LOG.info("Querying triple store for substation and voltage level positions");
```

2024-09-26 16:17 UTC, So-Fras commented on cgmes/cgmes-gl/src/main/java/com/powsybl/cgmes/gl/CgmesGLModel.java
> +    public static final String SUBSTATION_VL_POSITIONS_QUERY_KEY = "substationVoltageLevelPosition";
```suggestion
    public static final String SUBSTATION_VL_POSITION_QUERY_KEY = "substationVoltageLevelPosition";
```

2024-09-26 16:17 UTC, So-Fras commented on cgmes/cgmes-gl/src/main/java/com/powsybl/cgmes/gl/CgmesGLModel.java
> +        return queryTripleStore(SUBSTATION_VL_POSITIONS_QUERY_KEY);
```suggestion
        return queryTripleStore(SUBSTATION_VL_POSITION_QUERY_KEY);
```

2024-09-27 07:26 UTC, So-Fras approved these changes

2024-09-27 07:57 UTC, flo-dup commented on cgmes/cgmes-gl/src/main/java/com/powsybl/cgmes/gl/CgmesGLModel.java
> +    public PropertyBags getSubstationsVoltageLevelsPosition() {
`getSubstationVoltageLevelPositions()`

2024-09-27 08:13 UTC, merged