Switch test
powsybl/powsybl-core pull request #3181
Opened 2024-10-15 08:30 UTC by rcourtier

**Please check if the PR fulfills these requirements**
- [X] The commit message follows our guidelines
- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**
No

**What kind of change does this PR introduce?**
New unit tests

**What is the current behavior?**
Switch tests are using modified conformity networks

**What is the new behavior (if this is a feature change)?**
Switch tests are using simple networks

**Does this PR introduce a breaking change or deprecate an API?**
- [ ] Yes
- [X] No

**Other information**:

2025-01-15 13:09 UTC, olperr1 commented
`microGridBaseCaseNLSwitchWithoutName()` is mentioned in the description, but this method was not removed (and it is still used in `CgmesConformity1ModifiedConversionTest`).

2025-01-15 14:07 UTC, rcourtier commented
> `microGridBaseCaseNLSwitchWithoutName()` is mentioned in the description, but this method was not removed (and it is still used in `CgmesConformity1ModifiedConversionTest`).

Good point! I missed it, thanks for noticing.
It should be removed, as stated in the description. Testing of a switch without name is indeed done in commit f86a4b44237e02bd904c11739dbcf2e646e54e25 (Rework testing of basic switch conversion).

2025-01-23 08:39 UTC, olperr1 requested changes

2025-01-23 08:39 UTC, olperr1 commented on cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/SwitchConversionTest.java
> +        String eqFile = writeCgmesProfile(network, "EQ", tmpDir);
In the previously existing test (`testSwitchTypePreservedBusBranch`), the SSH profile was also checked.
Shouldn't it be the case here?

2025-01-23 08:39 UTC, olperr1 commented on cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/SwitchConversionTest.java
> +        String eqFile = writeCgmesProfile(network, "EQ", tmpDir);
Same thing with the old `testSwitchTypePreservedNodeBreaker`. I guess it is covered by the new `switchKindTest`, but the SSH profile isn't checked.

2025-01-24 14:37 UTC, rcourtier commented on cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/SwitchConversionTest.java
> +        String eqFile = writeCgmesProfile(network, "EQ", tmpDir);
Check of SSH profile has been added in commit 94d6e752d9a5387abeff1a9fa337a91ba56c1ef2

2025-01-24 14:45 UTC, rcourtier commented on cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/SwitchConversionTest.java
> +        assertEquals(SwitchKind.BREAKER, network.getSwitch("SW").getKind());
I don't feel that is absolutely neccary to precise that. The fact that BREAKER is the kind value for Switch is already described in SwitchConversion class:
``` java
    private SwitchKind kind() {
        String type = p.getLocal("type");
        return switch (type) {
            case "Disconnector", "GroundDisconnector", "Jumper" -> SwitchKind.DISCONNECTOR;
            case "LoadBreakSwitch" -> SwitchKind.LOAD_BREAK_SWITCH;
            default -> SwitchKind.BREAKER;  // Breaker, Switch, ProtectedSwitch
        };
    }
```
I can add it in here too if you think it's important to be noted.

2025-01-28 07:00 UTC, olperr1 commented on cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/SwitchConversionTest.java
> +        assertEquals(SwitchKind.BREAKER, network.getSwitch("SW").getKind());
It is indeed not necessary. It was only to highlight the fact that the default value was tested here, since some may think this assertion is redundant with the one on "BR".

2025-01-28 08:02 UTC, olperr1 requested changes

2025-01-28 08:02 UTC, olperr1 commented on cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/SwitchConversionTest.java
> +        String eqFile = writeCgmesProfile(network, "EQ", tmpDir);
The check of the SSH profile was only added in `switchKindTest`, and not in `switchInBusBranchTest`.
Was it on purpose?

2025-01-28 08:25 UTC, rcourtier commented on cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/SwitchConversionTest.java
> +        String eqFile = writeCgmesProfile(network, "EQ", tmpDir);
Yes, the fact that the correct class is restored at CGMES export is tested in `switchKindTest`. Here what's being tested is the retained attribute.

2025-01-29 09:10 UTC, olperr1 commented on cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/SwitchConversionTest.java
> +        assertEquals(SwitchKind.BREAKER, network.getSwitch("SW").getKind());
In fact, it is already stated, in the method comment, that SW is a "Switch" in CGMES (so it is sort of "untyped").

2025-01-29 09:21 UTC, olperr1 approved these changes

2025-01-29 09:22 UTC, merged