Add percent change load action
powsybl/powsybl-core pull request #3189
Opened 2024-10-23 13:48 UTC by bc-rte

**Please check if the PR fulfills these requirements**

- [X] The commit message follows our guidelines
- [X] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**

https://github.com/powsybl/powsybl-core/issues/3078

**What kind of change does this PR introduce?**

This PR adds a new action that allows users to change a load without knowing existing values, by specifying a percent P0 change and its impact on Q0.

**Does this PR introduce a breaking change or deprecate an API?**
- [ ] Yes
- [X] No

2024-10-30 10:21 UTC, olperr1 requested changes

2024-10-30 17:26 UTC, bc-rte commented on iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/PctLoadModification.java
> +            throw new PowsyblException(getMessageHeader() + ": Tried to apply modification on " + loadId + " but no load was found");
Wouldn't you find that the suggested message is not as precise?

If so, wouldn't it be better to favor that over consistency?

2024-10-30 17:33 UTC, bc-rte commented on iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/PctLoadModificationTest.java
> +    void shouldThrowWhenLoadDecreasesTooMuch() {
First case added.

Not sure what behaviour I should test in the second one.

2024-10-31 06:45 UTC, olperr1 commented on iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/PctLoadModificationTest.java
> +    void shouldThrowWhenLoadDecreasesTooMuch() {
Sorry, it wasn't clear enough. The second test I thought of was to check that when both arguments have non-zero values, both changes are applied.

2024-10-31 07:07 UTC, olperr1 commented
For the documentation, I suggest the following change in [`docs/simulation/security/index.md`](https://github.com/powsybl/powsybl-core/blob/fa2b1434bc56ab9bb4ecd5fb932339f4b61a6bc1/docs/simulation/security/index.md?plain=1#L42):

```diff
- - Change the active and/or reactive power of a load
+ - Change the active and/or reactive power of a load (by setting the values, or defining changes in value or percentage)
```

2024-10-31 09:29 UTC, olperr1 requested changes

2024-10-31 09:29 UTC, olperr1 commented on iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/PercentChangeLoadModification.java
> +        }
In fact, the exception should only be thrown when `throwException` is `true`.

There's a method for this:
```suggestion
        if (load == null) {
            logOrThrow(throwException, "Load '" + loadId + "' not found");
            return;
        }
```

2024-10-31 16:09 UTC, olperr1 requested changes

2024-10-31 16:09 UTC, olperr1 commented on iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/PercentChangeLoadModificationTest.java
> +        assertEquals(621.06, load.getP0());
When comparing doubles, it is a good practice to use a delta:

```suggestion
        assertEquals(621.06, load.getP0(), 0.01);
```

2024-11-20 16:14 UTC, alicecaron approved these changes

2024-11-21 08:23 UTC, merged