CGMES. Fix import of condensers
powsybl/powsybl-core pull request #3215
Opened 2024-11-19 10:11 UTC by zamarrenolm

**Please check if the PR fulfills these requirements**

- [X] The commit message follows our guidelines
- [X] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**

No

**What kind of change does this PR introduce?**

Bug fix

**What is the current behavior?**

In general, for all CIM versions, the `condenser` flag of the `Generator` objects was not set for synchronous machines of type (kind) condensers.
In CIM14 synchronous machines that were only condensers were not handled properly.

**What is the new behavior (if this is a feature change)?**
The `condenser` flag is set in the converged `Generators` if the type/kind of the synchronous machine is a condenser (and only a condenser).
CIM14 synchronous machines of type `condenser` are handled as condensers.

**Does this PR introduce a breaking change or deprecate an API?**
- [ ] Yes
- [X] No

**Other information**:

Bad handling of condensers in CIM14 was raised in #3214.

2024-11-22 11:55 UTC, rcourtier approved these changes

2024-12-03 09:10 UTC, olperr1 commented on cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/SynchronousMachineConversion.java
> +        adder.setCondenser(isCondenser);
After a second thought, we can keep it like this. I will just update the name/description to highlight the fact that this PR concerns all CIM versions.

2024-12-03 09:13 UTC, olperr1 approved these changes

2024-12-03 10:00 UTC, rcourtier requested changes

2024-12-03 10:00 UTC, rcourtier commented on cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/CondenserImportExportTest.java
> +        String eq = Files.readString(tmpDir.resolve(basename + "_EQ.xml"));
Can be simplified as follow:
`String eq = ConversionUtil.writeCgmesProfile(network, "EQ", tmpDir);`

2024-12-03 10:58 UTC, rcourtier requested changes

2024-12-03 10:58 UTC, rcourtier commented on cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/CondenserImportExportTest.java
> +        network.write("CGMES", null, tmpDir.resolve(basename));
You can remove that.

2024-12-03 10:58 UTC, rcourtier commented on cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/CondenserImportExportTest.java
>          network.write("CGMES", null, tmpDir.resolve(basename));
You can remove that.

2024-12-03 10:58 UTC, rcourtier commented on cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/CondenserImportExportTest.java
>          network.write("CGMES", null, tmpDir.resolve(basename));
You can remove that.

2024-12-03 12:04 UTC, rcourtier approved these changes

2024-12-03 12:13 UTC, merged