Refactor grouped queries in CgmesModel
powsybl/powsybl-core pull request #3238
Opened 2024-12-02 14:27 UTC by rcourtier

**Please check if the PR fulfills these requirements**

- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**

**What kind of change does this PR introduce?**

**What is the current behavior?**

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change or deprecate an API?**
- [ ] Yes
- [ ] No

**If yes, please check if the following requirements are fulfilled**

- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration steps are described in the following section

**What changes might users need to make in their application due to this PR? (migration steps)**

**Other information**:

2025-01-10 07:35 UTC, zamarrenolm commented on cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/transformers/AbstractTransformerConversion.java
> +            identifiable.addAlias(alias, aliasType);
why not keep using the `context.config().isEnsureIdAliasUnicity()` flag?

2025-01-10 07:35 UTC, zamarrenolm commented on cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/transformers/AbstractTransformerConversion.java
> +            identifiable.addAlias(alias, aliasType);
why not keep using the `context.config().isEnsureIdAliasUnicity()` flag?

2025-01-14 15:41 UTC, olperr1 requested changes

2025-01-14 15:41 UTC, olperr1 commented on cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/hvdc/Adjacency.java
> +                .map(t -> context.transformerEnds(t.getId("PowerTransformer")))
Could you use `CgmesNames.POWER_TRANSFORMER`? It could prevent typos.

2025-01-15 10:28 UTC, olperr1 requested changes

2025-01-16 08:47 UTC, olperr1 commented on cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/hvdc/Adjacency.java
> +                .map(t -> context.transformerEnds(t.getId("PowerTransformer")))
Sorry, I was not enough precise.
`"PowerTransformer"` is also used in the following classes:
- `Conversion`
- `NodeContainerMapping`
- `PhaseAngleClock`
- `NodeEquipment`

Could you replace it in these too?

2025-01-16 14:14 UTC, olperr1 commented on cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/hvdc/Adjacency.java
> +                .map(t -> context.transformerEnds(t.getId("PowerTransformer")))
Seen with @rcourtier: the `"PowerTransformer"` string here is the name of a variable in the property bag, but it is not required that it matches the CGMES class name. These are different concepts and using the same constant may be confusing.
The previous state could be restored (something better could be done, but it requires a global refactoring that could be done later).

2025-01-16 14:16 UTC, olperr1 commented on cgmes/cgmes-model/src/main/resources/CIM14.sparql
> +} ORDER BY ?PowerTransformer ?windingType
Sorry, I made a confusion here, I thought of `TransformerEnd.endNumber`. But CIM14 has not this concept.

2025-01-16 15:11 UTC, olperr1 approved these changes

2025-01-27 16:00 UTC, merged