Add fix to Matpower importer to import some pglib files
powsybl/powsybl-core pull request #3256
Opened 2024-12-19 13:12 UTC by geofjamg

**Please check if the PR fulfills these requirements**

- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**

No

**What kind of change does this PR introduce?**

Feature

**What is the current behavior?**

Some matpower files like pglib_opf_case1354_pegase.m from https://github.com/power-grid-lib/pglib-opf cannot be imported because the generator column count correspond to v1 format and not v2. 

**What is the new behavior (if this is a feature change)?**
We accept to read the file anyway even with missing columns.

**Does this PR introduce a breaking change or deprecate an API?**
- [ ] Yes
- [x] No

**If yes, please check if the following requirements are fulfilled**

- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration steps are described in the following section

**What changes might users need to make in their application due to this PR? (migration steps)**

**Other information**:

2024-12-20 08:20 UTC, caioluke commented on matpower/matpower-model/src/main/java/com/powsybl/matpower/model/MatpowerReader.java
> +            if (generators.getDimensions()[1] > MATPOWER_V1_GENERATORS_COLUMNS) {
generatorColumns  > MATPOWER_V1_GENERATORS_COLUMNS ?

2025-01-06 07:37 UTC, olperr1 commented on matpower/matpower-model/src/main/java/com/powsybl/matpower/model/MatpowerReader.java
> +            if (generators.getDimensions()[1] > MATPOWER_V1_GENERATORS_COLUMNS) {
`generatorColumns` is not defined in this method (`readGenerators`) but in `checkNumberOfColumns`.

2025-01-06 07:43 UTC, olperr1 commented on matpower/matpower-model/src/main/java/com/powsybl/matpower/model/MatpowerReader.java
> +            if (generators.getDimensions()[1] > MATPOWER_V1_GENERATORS_COLUMNS) {
As discussed together, it would be safer to use the following test here:
`if (generators.getDimensions()[1] >= MATPOWER_V2_GENERATORS_COLUMNS)`

=> 

- if dimension < `MATPOWER_V1_GENERATORS_COLUMNS`: error
- if dimension in `[ MATPOWER_V1_GENERATORS_COLUMNS ; MATPOWER_V2_GENERATORS_COLUMNS [`: considered as V1 format;
- if dimension >= `MATPOWER_V2_GENERATORS_COLUMNS`: considered as V2 format.

2025-01-07 10:06 UTC, olperr1 requested changes

2025-01-07 10:06 UTC, olperr1 commented on matpower/matpower-model/src/main/java/com/powsybl/matpower/model/MatpowerReader.java
> +            if (generatorColumnsToRead > 9) {
Here, the method will throw an exception in case of a generator table in v1 format (method called with `MATPOWER_V1_GENERATORS_COLUMNS` which equals 10).

But it may be clearer to have this test instead:
```suggestion
            if (generatorColumnsToRead == MATPOWER_V2_GENERATORS_COLUMNS) {
```

because it will be easier to relate it to the possible values for `generatorColumnsToRead`.

2025-01-07 12:42 UTC, geofjamg commented on matpower/matpower-model/src/main/java/com/powsybl/matpower/model/MatpowerReader.java
> +            if (generatorColumnsToRead > 9) {
I tried another design

2025-01-09 08:48 UTC, olperr1 commented on matpower/matpower-model/src/main/java/com/powsybl/matpower/model/MatpowerReader.java
> +            if (generatorColumnsToRead > 9) {
Thanks, it looks good to me.

2025-01-09 08:50 UTC, olperr1 approved these changes

2025-01-09 12:33 UTC, merged